name: Repository Mirroring

on:
    push:
        branches:
            - main

jobs:
    mirror:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout source repository
                uses: actions/checkout@v3
    
              - name: Mirror repository to Epitech repository
                uses: pixta-dev/repository-mirroring-action@v1
                with:
                  target_repo_url: git@github.com:moeruwaru/Chocolatine.git
                  target_repo_branch: main
                  ssh_private_key: SHA256:i1RHvg+m16GxIUeGbdewTNHze8aaw7G6Fm7zNcr/SNo