name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.TARGET_REPO_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }} 
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.TARGET_REPO_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
          ssh_username:
            git
