name: Repository Mirroring

on:
    push:
        branches:
            - main

jobs:
    mirror:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v3

            - name: Mirror repository to Epitech repository
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ secrets.TARGET_REPO_URL }}
                ssh_private_key: ${{ secrets.SSH_KEY }}